### ISSUE TITLE
https://issuer-demo.polygonid.me/main - throwing bad gateway 

### ISSUE THREAD

**Issue by Asthay97** [oceans404/fullstack-polygon-id-vc-gated-dapp#2]
When i am trying to self issue using the self issuer url its throwing bad gateway error: 
<img width="1440" alt="Screenshot 2023-12-09 at 10 20 29 AM" src="https://github.com/oceans404/fullstack-polygon-id-vc-gated-dapp/assets/75947851/a490363f-7491-48e5-9d95-b38b6a864502">
I have tried different browsers still its throwing this error

**Comment by oceans404** [comment]
The self issuer is back up https://issuer-ui.polygonid.me/
